name: createGeoJson
on:
  workflow_dispatch:
  schedule:
    - cron: '*/15 * * * *'
  
jobs:
  createGeoJson-job:
    runs-on: ubuntu-latest
    steps: 
      - name: checkout
        uses: actions/checkout@v2
      - name: produce geojson
        shell: pwsh
        run: ./createGeoJson.ps1
        working-directory: ./.github/workflows
      - name: set CURRENT_BRANCH
        run: echo "CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)" >> $GITHUB_ENV
      - name: commit files
        working-directory: ./
        run: |
          git config --global user.name 'atlantis-green'
          git config --global user.email 'atlantis-green@users.noreply.github.com'
          git status
          git add .
          git stash
          git checkout data
          cd ./data
          rm * -r
          git stash pop
          git add . 
          git commit -m "Update the data"
          git push -u origin HEAD

