name: createGeoJson
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '*/15 * * * *'

jobs:
  createGeoJson-job:
    runs-on: ubuntu-latest
    steps:
      # prepare and save the files in git
      - name: checkout
        uses: actions/checkout@v2
      - name: produce geojson
        id: produce-geojson
        shell: pwsh
        run: ./createGeoJson.ps1
        working-directory: ./.github/workflows
      - name: set CURRENT_BRANCH and do git prep steps
        if: always()
        run: |
          echo "CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)" >> $GITHUB_ENV
          git config --global user.name 'atlantis-green'
          git config --global user.email 'atlantis-green@users.noreply.github.com'
          git add .
          git commit -m "Update the data"
          git fetch
      - name: commit files to data branch
        run: git switch data
      - name: commit files to the error branch if produce-geojson failed
        if:  ${{ steps.produce-geojson.conclusion == 'failure'}}
        run: git switch error
      - name: finish committing the stuff
        if: always()
        run: |
          cd ./data
          rm * -r
          git cherry-pick ${{ env.CURRENT_BRANCH }} --strategy-option=theirs
          git push -u origin HEAD
      - name: download the geojson schema
        run: curl https://geojson.org/schema/GeoJSON.json --output ./GeoJSON.json
# commented out -- more details in #11 -- https://github.com/marknooch/foodtrucks/issues/11
#      - name: confirm we produced valid GeoJSON
#        uses: nhalstead/validate-json-action@0.1.3
#        with:
#          schema: ./GeoJSON.json
#          jsons: /data/openFoodTrucks.json
      
      # now we move the files to s3
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: deploy data to s3
        run: aws s3 sync ./data s3://${{ secrets.S3_BUCKET }}


